# Generated by Django 4.0.3 on 2022-06-05 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20, verbose_name='Nombre de la tarea')),
                ('description', models.CharField(max_length=200, verbose_name='Descripcion de la tarea')),
                ('priority', models.CharField(choices=[('high', 'ALTA'), ('medium', 'MEDIA'), ('low', 'BAJA')], default='low', max_length=10, verbose_name='Prioridad de la tarea')),
                ('date_finish', models.DateTimeField(verbose_name='Fecha de finalizacion de la tarea')),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('user_modified', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
